name: test-deploy-package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # modified from https://github.com/pypa/pip/blob/main/.github/workflows/ci.yml
  ci:

    name: test / ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: true
      matrix:
        os: [ Ubuntu ]
        python:
          - 3.9

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Ubuntu dependencies
        if: matrix.os == 'Ubuntu'
        run: sudo apt-get install bzr

      - name: Check pip installation
        run: |
          pip install codino

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest tests/ --cov=codino --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml

      - name: Build documentation
        run: poetry run make html --directory docs/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
